//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWebApp.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Required]

        public string EmployeeID { get; set; }
        [Required]

        public string LastName { get; set; }
        [Required]

        public string FirstName { get; set; }
        [DisplayFormat(DataFormatString = "{0:dd-mm-yyyy}")]
        [DataType(DataType.Date)]

        public System.DateTime DOB { get; set; }
        [Required]

        public string Department { get; set; }
    }
    public partial class Employee
    {
        public string FullName
        {
            get
            {
                return FirstName + " " + LastName;
            }
        }
    }
}
