//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BasicWebApp.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class LoginDetail
    {

        [Display(Name = "User Name")]
        [Required(ErrorMessage = "This field is required.")]
        public string Username { get; set; }

        [DataType(DataType.Password)]
        [Required(ErrorMessage = "This field is required.")]

        public string Password { get; set; }
       [Required(ErrorMessage = "Please select")]
        public string Userrole { get; set; }

    }

    public partial class LoginDetail
    {
        public string ErrorMessage { get; set; }
    }
}
